[build]
  publish = "dist"

[functions]
  directory = "functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/reviews/*"
  to = "/index.html?page=reviews"
  status = 200

[[redirects]]
  from = "/reviews"
  to = "/index.html?page=reviews"
  status = 200
