[build]
  publish = "dist"
  command = "npm install"

[build.environment]
  NODE_VERSION = "20"

[functions]
  directory = "functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/reviews/*"
  to = "/index.html?page=reviews"
  status = 200

[[redirects]]
  from = "/reviews"
  to = "/index.html?page=reviews"
  status = 200
